language: cpp
sudo: required
dist: xenial
compiler:
    - gcc
os:
    - linux

notifications:
  email:
    recipients:
      - xyp8023@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

before_install:
    - env | sort
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake qtdeclarative5-dev qt5-qmake libqglviewer-dev libeigen3-dev libsuitesparse-dev python3-setuptools
    - which python3
    - pyenv global 3.6.7
    - PY_CMD=/usr/bin/python3
    - $PY_CMD -m pip install -U numpy scikit-learn scipy matplotlib setuptools

install: 
    - git clone https://github.com/uoip/g2opy.git
script:
    - cd g2opy && mkdir build && cd build 
    - cmake -DPYTHON_EXECUTABLE=$PY_CMD .. 
    - make -w -j8
    - cd .. && sudo $PY_CMD setup.py install
    - cd .. && sudo $PY_CMD setup.py install
    - $PY_CMD -m unittest tests.test_icp
    - $PY_CMD -m unittest tests.test_read_data
    - ABSDIR=`readlink -e ./g2opy`
    - export PYTHONPATH=$PYTHONPATH:$ABSDIR
    - $PY_CMD graph_slam.py intel 0.1

 
