language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
os:
    - linux

notifications:
  email:
    recipients:
      - xyp8023@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

before_install:
    - env | sort
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake qtdeclarative5-dev qt5-qmake libqglviewer-dev libeigen3-dev libsuitesparse-dev

install: 
    - git clone https://github.com/uoip/g2opy.git
script:
    - cd g2opy && mkdir build && cd build 
    - cmake ..
    - cat g2o/config.h
    - make 
    - cd .. 
    - python3 setup.py install
 
