language: cpp
sudo: required
dist: xenial
compiler:
    - gcc
os:
    - linux

notifications:
  email:
    recipients:
      - xyp8023@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

before_install:
    - env | sort
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake qtdeclarative5-dev qt5-qmake libqglviewer-dev libeigen3-dev libsuitesparse-dev python3-setuptools
    - which python3
    - pyenv global 3.6.7
    - pip3 install -U numpy scikit-learn scipy

install: 
    - git clone https://github.com/uoip/g2opy.git
script:
    - cd g2opy && mkdir build && cd build 
    - cmake -DPYTHON_EXECUTABLE=$(which python3) .. 
    - cat g2o/config.h
    - make -w -j8
    - cd .. && sudo python3 setup.py install
    - cd .. && sudo python3 setup.py install
    - python3 -m unittest tests.test_icp
    - python3 -m unittest tests.test_read_data
    - python3 graph_slam.py intel 0.1

 
